config_version: 0.0
aws:
  rolename: Aardvark
  region: us-east-1
  arn_partition: aws
updater:
  num_threads: 5
  failing_arns: {}
sqlalchemy:
  database_uri: sqlite:///./aardvark.db
  track_modifications: false
swag:
  bucket: swag-data
  opts:
    swag.schema_version: 2
    swag.type: s3
    swag.bucket_name: swag-data
    swag.data_file: v2/accounts.json
    swag.region: us-east-1
  filter: ""
  service_enabled_requirement: ""
logging:
  disable_existing_loggers: false
  formatters:
    standard:
      format: '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: DEBUG
      stream: ext://sys.stdout
    file:
      backupCount: 100
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: aardvark.log
      formatter: standard
      level: DEBUG
      maxBytes: 10485760
  loggers:
    aardvark:
      handlers:
        - file
        - console
      level: DEBUG
    gunicorn:
      handlers:
        - file
        - console
      level: DEBUG
    asyncio:
      handlers:
        - console
      level: DEBUG
  version: 1
